UniversityManagementSystemWebApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class CourseController : Controller
    {
        private CourseManager courseManager;
        private List<Semester> semesters;
        private List<Department> departments;
        private StudentManager studentManager;

        public CourseController()
        {
            courseManager = new CourseManager();
            semesters = new List<Semester>();
            departments = new List<Department>();
            studentManager = new StudentManager();
        }
        //
        // GET: /Course/
        [HttpGet]
        public ActionResult Save()
        {
            semesters = courseManager.GetAllSemesters();
            departments = courseManager.GetAllDepartments();
            ViewBag.Semesters = semesters;
            ViewBag.Departments = departments;
            return View();
        }
        [HttpPost]
        public ActionResult Save(Course course)
        {
            bool isCourseExist = false;
            if (ModelState.IsValid)
            {
                string message;
                isCourseExist = courseManager.IsCourseExist(course);
                if (isCourseExist)
                {
                    message = "This course is already exists.";
                    ViewBag.Message = message;
                }
                else
                {
                    message = courseManager.Save(course);
                    ViewBag.Message = message;
                }
                ModelState.Clear();
            }
            else
            {
                ViewBag.Message = "Model state is invalid!";
            }
            semesters = courseManager.GetAllSemesters();
            departments = courseManager.GetAllDepartments();
            ViewBag.Semesters = semesters;
            ViewBag.Departments = departments;
            ViewBag.IsCourseExist = isCourseExist;
            return View();
        }
        [HttpGet]
        public ActionResult EnrollCourse()
        {
            ViewBag.StudentInfo = studentManager.GetStudentInfo();
            return View();
        }
        [HttpPost]
        public ActionResult EnrollCourse(EnrollCourse enrollCourse)
        {
            bool isCourseEnrolled = false;
            if (ModelState.IsValid)
            {
                string message;
                isCourseEnrolled = courseManager.IsCourseEnrolled(enrollCourse);
                if (isCourseEnrolled)
                {
                    message = "Course enrolled before!";
                    ViewBag.Message = message;
                }
                else
                {
                    message = courseManager.SaveEnrolledCourse(enrollCourse);
                    ViewBag.Message = message;
                }
                ModelState.Clear();
            }
            else
            {
                ViewBag.Message = "Model state is invalid!";
            }
            ViewBag.IsCourseEnrolled = isCourseEnrolled;
            ViewBag.StudentInfo = studentManager.GetStudentInfo();
            return View();
        }
        public JsonResult GetStudentInfoByStudentId(int? studentId)
        {
            var student = studentManager.GetStudentInfoByStudentId(studentId);
            return Json(student);
        }
        public JsonResult GetDepartmentByStudentId(int? studentId)
        {
            var department = studentManager.GetDepartmentByStudentId(studentId);
            return Json(department);
        }
        public JsonResult GetAllCourses(int? studentId)
        {
            Department department = studentManager.GetDepartmentByStudentId(studentId);
            var courses = courseManager.GetAllCoursesByDepartmentId(department.Id);
            return Json(courses);
        }
    }
}

UniversityManagementSystemWebApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class StudentController : Controller
    {
        private DepartmentManager departmentManager;
        private StudentManager studentManager;
        private ResultManager resultManager;

        public StudentController()
        {
            departmentManager = new DepartmentManager();
            studentManager = new StudentManager();
            resultManager = new ResultManager();
        }
        //
        // GET: /Student/
        [HttpGet]
        public ActionResult SaveStudent()
        {
            string currentDate = DateTime.Today.ToString("dd/MM/yyyy");
            ViewBag.CurrentDate = currentDate;
            ViewBag.Departments = departmentManager.GetAllDepartments();
            return View();
        }
        [HttpPost]
        public ActionResult SaveStudent(Student student)
        {
            bool isStudentExist = false;
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                string message;
                isStudentExist = studentManager.IsStudentExist(student.Email);
                if (isStudentExist)
                {
                    message = "Student already exist!";
                    ViewBag.Message = message;
                }
                else
                {
                    message = studentManager.Save(student);
                    ViewBag.StudentInfo = studentManager.GetStudent(student);
                    Department department = studentManager.GetDepartmentInfoByDepartmentId(student.DepartmentId);
                    ViewBag.DepartmentName = department.Name;
                    ViewBag.Message = message;
                }
                ModelState.Clear();
            }
            else
            {
                ViewBag.Message = "Model state is invalid!";
            }
            ViewBag.CurrentDate = DateTime.Today.ToString("dd/MM/yyyy");
            ViewBag.Departments = departmentManager.GetAllDepartments();
            ViewBag.IsStudentExist = isStudentExist;
            return View();
        }
        [HttpGet]
        public ActionResult StudentResult()
        {
            ViewBag.Grades = studentManager.GetAllGrades();
            ViewBag.StudentInfo = studentManager.GetStudentInfo();
            return View();
        }
        [HttpPost]
        public ActionResult StudentResult(StudentResult studentResult)
        {
            bool isResultExist = false;
            if (ModelState.IsValid)
            {
                string message;
                isResultExist = resultManager.IsResultExist(studentResult);
                if (isResultExist)
                {

                    message = resultManager.UpdateResult(studentResult);
                    ViewBag.Message = message;
                }
                else
                {
                    message = resultManager.Save(studentResult);
                    ViewBag.Message = message;
                }
                ModelState.Clear();
            }
            else
            {
                ViewBag.Message = "Model state is invalid!";
            }
            ViewBag.IsResultExist = isResultExist;
            ViewBag.Grades = studentManager.GetAllGrades();
            ViewBag.StudentInfo = studentManager.GetStudentInfo();
            return View();
        }
        [HttpGet]
        public ActionResult ViewResult()
        {
            List<Student> students = studentManager.GetStudentInfoByEnrollCourses();
            ViewBag.StudentInfo = students;
            return View();
        }
        [HttpPost]
        public ActionResult ViewResult(StudentResult studentResult)
        {
            ViewBag.StudentInfo = studentManager.GetStudentInfoByEnrollCourses();
            return View();
        }

        public ActionResult CreateResult(StudentResult studentResult)
        {
            var studentInfo = studentManager.GetStudentInfoByStudentId(studentResult.StudentId);
            var department = studentManager.GetDepartmentByStudentId(studentResult.StudentId);
            var result = studentManager.GetStudentResultByStudentId(studentResult.StudentId);
            if (result.Count == 0)
            {
                ViewBag.Message = "No result found!";
            }
            else
            {
                ViewBag.StudentInfo = studentInfo;
                ViewBag.Department = department;
                ViewBag.Result = result;
                double totalCredit = 0.00d, totalPoint = 0.00d, point;
                foreach (var value in result)
                {
                    totalCredit += value.Credit;
                    point = Convert.ToDouble(value.GradePoint);
                    totalPoint += point * value.Credit;
                }
                string cgpa = Convert.ToString(totalPoint / totalCredit);
                if (cgpa.Length < 4)
                {
                    ViewBag.CGPA = cgpa + ".00";
                }
                else
                {
                    ViewBag.CGPA = cgpa.Substring(0, 4);
                }

            }
            return View();
        }
        public ActionResult ResultSheet(StudentResult studentResult)
        {
            return new ActionAsPdf("CreateResult", studentResult);
        }



        public JsonResult GetStudentInfoByStudentId(int? studentId)
        {
            var student = studentManager.GetStudentInfoByStudentId(studentId);
            return Json(student);
        }
        public JsonResult GetDepartmentByStudentId(int? studentId)
        {
            var department = studentManager.GetDepartmentByStudentId(studentId);
            return Json(department);
        }
        public JsonResult GetAllCoursesEnrolledByStudentId(int? studentId)
        {
            var courses = studentManager.GetAllCoursesEnrolledByStudentId(studentId);
            return Json(courses);
        }
        public JsonResult GetStudentResultByStudentId(int? studentId)
        {
            var studentResult = studentManager.GetStudentResultByStudentId(studentId);
            return Json(studentResult);
        }
    }
}

UniversityManagementSystemWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@ViewBag.Title - University Management System</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">

                    <img src="~/Content/Images/logo.jpg" />

                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Department
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Department", "Save", "Department")</li>
                            <li>@Html.ActionLink("View Departments", "ViewAllDepartment", "Department")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Course
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Course", "Save", "Course")</li>
                            <li>@Html.ActionLink("Assign Courses", "AssignCourse", "AssignCourse")</li>
                            <li>@Html.ActionLink("Enroll Courses", "EnrollCourse", "Course")</li>
                            <li>@Html.ActionLink("Course Statics", "CourseStatistics", "CourseStatistics")</li>
                            <li>@Html.ActionLink("Unassign Courses", "UnAssignCourses", "AssignCourse")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Teacher
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Teacher", "Save", "Teacher")</li>
                            @*<li>@Html.ActionLink("Assign Courses", "AssignCourse", "AssignCourse")</li>*@
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Student
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register Student", "SaveStudent", "Student")</li>
                            @*<li>@Html.ActionLink("Enroll Courses", "EnrollCourse", "Course")</li>*@
                            <li>@Html.ActionLink("Save Result", "StudentResult", "Student")</li>
                            <li>@Html.ActionLink("View Result", "ViewResult", "Student")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Manage Rooms
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Allocate Class Room", "AllocateClassRoom", "AllocateClassRoom")</li>
                            <li>@Html.ActionLink("Class Schedule & Room Allocation Information", "ViewClassRoomAllocation", "AllocateClassRoom")</li>
                            <li>@Html.ActionLink("Unallocate Classrooms", "UnallocateClassRoom", "AllocateClassRoom")</li>
                        </ul>
                    </li>

                    @*<li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Save & Register
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Department", "Save", "Department")</li>
                                <li>@Html.ActionLink("Save Course", "Save", "Course")</li>
                                <li>@Html.ActionLink("Save Teacher", "Save", "Teacher")</li>
                                <li>@Html.ActionLink("Register Student", "SaveStudent", "Student")</li>
                                <li>@Html.ActionLink("Save Result", "StudentResult", "Student")</li>
                            </ul>
                        </li>*@

                    @*<li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Course Assignment & Room Allocation
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Assign Courses", "AssignCourse", "AssignCourse")</li>
                            <li>@Html.ActionLink("Enroll Courses", "EnrollCourse", "Course")</li>
                            <li>@Html.ActionLink("Allocate Class Room", "AllocateClassRoom", "AllocateClassRoom")</li>
                        </ul>
                    </li>


                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            View
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Departments", "ViewAllDepartment", "Department")</li>
                            <li>@Html.ActionLink("Course Statics", "CourseStatistics", "CourseStatistics")</li>
                            <li>@Html.ActionLink("Class Schedule & Room Allocation Information", "ViewClassRoomAllocation", "AllocateClassRoom")</li>
                            <li>@Html.ActionLink("Result", "ViewResult", "Student")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Others
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Unassign Courses", "UnAssignCourses", "AssignCourse")</li>
                            <li>@Html.ActionLink("Unallocate Classrooms", "UnallocateClassRoom", "AllocateClassRoom")</li>
                        </ul>
                    </li>*@
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="container"></div>
        <div class="footer">
            <footer>
                <h5>&copy; @DateTime.Now.Year - University Management System</h5>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("scriptsForClear", required: false)
</body>
</html>